kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "build.openshift.io"
        version: "v1"
        kind: "BuildConfig"
      metrics:
        - name: "openshift_buildconfig_created"
          help: "Unix creation timestamp"
          each:
            type: Gauge
            gauge:
              path: [metadata]
              labelsFromPath:
                buildconfig: [name]
                namespace: [namespace]
              valueFrom: [creationTimestamp]
        - name: "openshift_buildconfig_metadata_generation"
          help: "Sequence number representing a specific generation of the desired state."
          each:
            type: Gauge
            gauge:
              path: [metadata]
              labelsFromPath:
                buildconfig: [name]
                namespace: [namespace]
              valueFrom: [generation]
        - name: "openshift_buildconfig_status_latest_version"
          help: "The latest version of buildconfig."
          each:
            type: Gauge
            gauge:
              path: [status]
              valueFrom: [lastVersion]
          labelsFromPath:
            buildconfig: [metadata, name]
            namespace: [metadata, namespace]
        - name: "openshift_buildconfig_labels"
          help: "Kubernetes labels converted to Prometheus labels."
          each:
            type: Info
            info:
              path: [metadata]
              labelsFromPath:
                buildconfig: [name]
                namespace: [namespace]
                "*": [labels]
