global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:8080"]
    relabel_configs:
      - regex: "customresource_group|customresource_kind|customresource_version"
        action: "labeldrop"
